[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "python-telegram-bot==20.7",
    "telegram>=0.0.1",
    "yt-dlp>=2025.1.26",
]
